///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CategoryModel {
/*
{
  "_id": "643001e7805219f7ffe2951c",
  "slug": "body-care-31",
  "title": "BODY CARE",
  "level": 1,
  "parentId": "6401b397ffad22a68c17dbda"
} 
*/

  String? id;
  String? slug;
  String? title;
  int? level;
  String? parentId;

  CategoryModel({
    this.id,
    this.slug,
    this.title,
    this.level,
    this.parentId,
  });
  CategoryModel.fromJson(Map<String, dynamic> json) {
    id = json['_id']?.toString();
    slug = json['slug']?.toString();
    title = json['title']?.toString();
    level = json['level']?.toInt();
    parentId = json['parentId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = id;
    data['slug'] = slug;
    data['title'] = title;
    data['level'] = level;
    data['parentId'] = parentId;
    return data;
  }
}

class CustomBrandModel {
/*
{
  "_id": "643675e6f36d227e3566b71a",
  "slug": "mesauda-14",
  "name": "MESAUDA"
} 
*/

  String? id;
  String? slug;
  String? name;
  bool? isSelected;

  CustomBrandModel({
    this.id,
    this.slug,
    this.name,
    this.isSelected,
  });
  CustomBrandModel.fromJson(Map<String, dynamic> json) {
    id = json['_id']?.toString();
    slug = json['slug']?.toString();
    name = json['name']?.toString();
    isSelected = false;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = id;
    data['slug'] = slug;
    data['name'] = name;
    isSelected = false;

    return data;
  }
}

class SomeRootEntityDataFilterOptions {
/*
{} 
*/

  SomeRootEntityDataFilterOptions.fromJson(Map<String, dynamic> json) {}
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    return data;
  }
}

class PriceRangeModel {
/*
{
  "min": 320,
  "max": 50000
} 
*/

  int? min;
  int? max;

  PriceRangeModel({
    this.min,
    this.max,
  });
  PriceRangeModel.fromJson(Map<String, dynamic> json) {
    min = json['min']?.toInt();
    max = json['max']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['min'] = min;
    data['max'] = max;
    return data;
  }
}

// class SomeRootEntityDataCategoryDetail {
// /*
// {
//   "title": "SKIN",
//   "slug": "skin"
// }
// */

//   String? title;
//   String? slug;

//   SomeRootEntityDataCategoryDetail({
//     this.title,
//     this.slug,
//   });
//   SomeRootEntityDataCategoryDetail.fromJson(Map<String, dynamic> json) {
//     title = json['title']?.toString();
//     slug = json['slug']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['title'] = title;
//     data['slug'] = slug;
//     return data;
//   }
// }

class CategoryFilterModel {
  // SomeRootEntityDataCategoryDetail? categoryDetail;
  PriceRangeModel? priceRange;
  List<int?>? offPercentRange;
  SomeRootEntityDataFilterOptions? filterOptions;
  List<CustomBrandModel?>? brands;
  List<CategoryModel?>? categories;

  CategoryFilterModel({
    // this.categoryDetail,
    this.priceRange,
    this.offPercentRange,
    this.filterOptions,
    this.brands,
    this.categories,
  });
  CategoryFilterModel.fromJson(Map<String, dynamic> json) {
    // categoryDetail = (json['categoryDetail'] != null)
    //     ? SomeRootEntityDataCategoryDetail.fromJson(json['categoryDetail'])
    //     : null;
    priceRange = (json['priceRange'] != null)
        ? PriceRangeModel.fromJson(json['priceRange'])
        : null;
    if (json['offPercentRange'] != null) {
      final v = json['offPercentRange'];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      offPercentRange = arr0;
    }
    filterOptions = (json['filterOptions'] != null)
        ? SomeRootEntityDataFilterOptions.fromJson(json['filterOptions'])
        : null;
    if (json['brands'] != null) {
      final v = json['brands'];
      final arr0 = <CustomBrandModel>[];
      v.forEach((v) {
        arr0.add(CustomBrandModel.fromJson(v));
      });
      brands = arr0;
    }
    if (json['categories'] != null) {
      final v = json['categories'];
      final arr0 = <CategoryModel>[];
      v.forEach((v) {
        arr0.add(CategoryModel.fromJson(v));
      });
      categories = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    // if (categoryDetail != null) {
    //   data['categoryDetail'] = categoryDetail!.toJson();
    // }
    if (priceRange != null) {
      data['priceRange'] = priceRange!.toJson();
    }
    if (offPercentRange != null) {
      final v = offPercentRange;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['offPercentRange'] = arr0;
    }
    if (filterOptions != null) {
      data['filterOptions'] = filterOptions!.toJson();
    }
    if (brands != null) {
      final v = brands;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['brands'] = arr0;
    }
    if (categories != null) {
      final v = categories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['categories'] = arr0;
    }
    return data;
  }
}

class CategoryFilterOuterModel {
  String? title;
  CategoryFilterModel? data;

  CategoryFilterOuterModel({
    this.title,
    this.data,
  });
  CategoryFilterOuterModel.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    data = (json['data'] != null)
        ? CategoryFilterModel.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
